/* =============================================================================
 * CONFIG — ЭНД БҮХ ЗҮЙЛИЙГ ӨӨРЧИЛНӨ ҮҮ  /  EDIT EVERYTHING HERE
 * -----------------------------------------------------------------------------
 * Энэ нэг файлд хүлээн авагчийн нэр, илгээгчийн нэр, захидлын текст, зураг,
 * бялууны дурсамж, хөгжмийг тохируулна. Өөр газар кодыг засах шаардлагагүй.
 *
 * This single file controls recipient/sender names, the letter text, the secret
 * cake photos, and music. You should not need to edit anything else.
 * ========================================================================== */

export const CONFIG = {
  /* --- Хүн / People ------------------------------------------------------- */
  recipientName: 'Сараа', //  Хүлээн авагчийн нэр / Recipient's name
  senderName: 'Бат', //       Илгээгчийн нэр / Sender's name

  /* --- Захидал / The letter ---------------------------------------------- *
   * Мөр бүр тусдаа дэлгэгдэнэ. Шинэ мөр нэмэхдээ массивт мөр нэмнэ үү.
   * Each line is revealed separately. Add a new line by adding an array item.
   * Mongolian Cyrillic renders correctly with the configured fonts.            */
  letter: {
    greetingTemplate: 'Хайрт {name} минь,', //  {name} → recipientName
    lines: [
      'Өнөөдөр чиний төрсөн өдөр —',
      'миний хувьд жилийн хамгийн дулаахан өдөр.',
      'Чамтай хамт өнгөрүүлсэн мөч бүр',
      'миний зүрхэнд гэрэл болон үлддэг.',
      'Чиний инээд, чиний дулаан сэтгэл,',
      'намайг үргэлж урагшлуулдаг.',
      'Энэ жил чамд баяр баясгалан,',
      'эрүүл энх, хайр дүүрэн байхыг хүсье.',
    ],
    signoffTemplate: 'Хайртай чинь, {sender}', //  {sender} → senderName
  },

  /* --- Дурсамж / Polaroid gallery ---------------------------------------- *
   * Зургийн файлуудаа /public/images дотор хийгээд энд нэр, тайлбарыг бичнэ үү.
   * Drop your photos into /public/images and list filename + caption here.      */
  photos: [
    { src: '/images/photo-1.svg', caption: 'Бидний анхны зураг' },
    { src: '/images/photo-2.svg', caption: 'Тэр зуны өдөр' },
    { src: '/images/photo-3.svg', caption: 'Чиний инээмсэглэл' },
    { src: '/images/photo-4.svg', caption: 'Хамтдаа аялсан нь' },
    { src: '/images/photo-5.svg', caption: 'Хайрт мөчүүд' },
  ],

  /* --- Дуу / Music -------------------------------------------------------- *
   * Файлаа /public/audio дотор хийгээд нэрийг нь энд бичнэ үү.
   * Put your file in /public/audio and write its filename here.                 */
  // NB: placeholders are .wav (generated by scripts/gen-audio.mjs). When you
  // swap in your own .mp3/.ogg files, just update these paths to match.
  audio: {
    music: '/audio/bg-music.wav', //  Дэвсгэр хөгжим / Background music
    dialClick: '/audio/dial-click.wav', //  Дугуй эргэх чимээ / Dial tick
    unlock: '/audio/unlock.wav', //  Цоож онгойх / Unlock
    pageTurn: '/audio/page-turn.wav', //  Хуудас эргэх / Page turn
    musicVolume: 0.45,
  },

  /* --- Төрсөн өдрийн бялуу / Orbiting photo-cake scene ------------------- *
   * Бялууг тойрон эргэлдэх зургууд. Зураг бүрийн ард нуугдсан тэмдэглэл бий:
   * src (зураг), noteTitle (гарчиг), noteMessage (мессеж).
   * Photos that orbit the cake in 3D. Each hides a note: src + title + message. *
   * orbitSpeed = эргэлтийн хурд (зэрэг/фрейм), photoCount = хэдэн зураг харуулах. */
  cake: {
    // Бодит бялууны зураг (ил тод дэвсгэртэй PNG) /public/images дотор хийнэ.
    // Хоосон бол CSS-ээр зурсан бялуу харагдана.
    // Realistic cake cutout (transparent-background PNG) in /public/images.
    // Leave '' (empty) to use the built-in CSS cake instead.
    cakeImage: '', //  '' → цэвэрхэн CSS бялуу. Бодит зураг бол watermark-гүй,
    //                  ил тод дэвсгэртэй PNG-ийн зам бичнэ үү. e.g. '/images/cake.png'
    orbitSpeed: 0.18, //  Суурь эргэлтийн хурд / base spin (deg per frame)
    photoCount: 6, //     Тойрог дахь зургийн тоо / how many cards in the orbit
    photos: [
      {
        src: '/images/photo-1.svg',
        noteTitle: 'Анхны уулзалт',
        noteMessage: 'Чамайг анх харсан тэр өдрийг би хэзээ ч мартахгүй.',
      },
      {
        src: '/images/photo-2.svg',
        noteTitle: 'Зуны аялал',
        noteMessage: 'Нар жаргах үеийн чиний инээд хамгийн үзэсгэлэнтэй байсан.',
      },
      {
        src: '/images/photo-3.svg',
        noteTitle: 'Чиний инээмсэглэл',
        noteMessage: 'Чиний инээмсэглэл миний хамгийн дуртай гэрэл.',
      },
      {
        src: '/images/photo-4.svg',
        noteTitle: 'Хамтдаа',
        noteMessage: 'Чамтай хамт байх бүр мөч надад бэлэг шиг санагддаг.',
      },
      {
        src: '/images/photo-5.svg',
        noteTitle: 'Хайрт мөчүүд',
        noteMessage: 'Эдгээр дурсамжийг чамтай хамт цуглуулсандаа баяртай байна.',
      },
      {
        src: '/images/photo-6.svg',
        noteTitle: 'Ирээдүй',
        noteMessage: 'Урагшаа бид олон сайхан дурсамж бүтээх болно. Хайртай шүү.',
      },
    ],
  },

  /* --- Төгсгөл / Finale --------------------------------------------------- */
  finaleTitleTemplate: 'Төрсөн өдрийн мэнд хүргэе, {name}!',
  // Сүүлчийн сэтгэл хөдөлгөм мөр — ирээдүйн амлалт/хүсэл.
  // The final emotional line — a wish/promise for the future.
  finaleWish: 'Дараагийн төрсөн өдрүүдийг чинь ч бас хамтдаа угтмаар байна.',
  // Сонголтоор: төгсгөлд гарах нэг зураг (хоосон бол гарахгүй).
  // Optional: one closing photo on the finale ('' → none).
  finalePhoto: '',
};

/* Туслах: загвар дотор {name}/{sender}-г орлуулна / fill {name},{sender} */
export function fill(template) {
  return template
    .replace('{name}', CONFIG.recipientName)
    .replace('{sender}', CONFIG.senderName);
}
